# Numpy 

Numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

Numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

**Official Website :-**

https://numpy.org/doc/stable/user/basics.html

## Install Numpy 

pip install numpy

## Import numpy 

In [1]:
import numpy as np 

## Creating Arrays 

In [2]:
# Let's start with one dimensional array which is also called as vector 

vec = np.array([1,2,3])
print(vec)

[1 2 3]


In [3]:
# We can also create muli dimensional arrays by converting the lists of lists. Multi dimensional arrays are also called matrix
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [4]:
# creating arrays using the arange method 
vec2 = np.arange(0,15)
print(vec2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
# Creating the numpy array using the arange method along with step size
vec3 = np.arange(3,21,6)
print(vec3)

[ 3  9 15]


In [6]:
# Creating arrays using the linspace method 
vec4 = np.linspace(0,5,10)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [7]:
# We can also reshape the arrays
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [8]:
# To flatten the array into single dimension
vec4_reshaped.ravel()

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [9]:
# Using the zeroes method 
mat2 = np.zeros([5,3])
print(mat2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Using the ones method 

mat3 = np.ones((3,5))
print(mat3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
# Eye method 
mat4 = np.eye(5)
print(mat4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##  Maths Functions 

In [14]:
rand_arr = np.random.rand(5,5)
rand_arr

array([[0.04836202, 0.47515613, 0.68620383, 0.0693193 , 0.47258702],
       [0.93633212, 0.52978533, 0.51094005, 0.14810508, 0.19461213],
       [0.94121222, 0.91929442, 0.85673321, 0.49717124, 0.50485445],
       [0.20713655, 0.83340237, 0.80126429, 0.75208897, 0.13026511],
       [0.35325222, 0.79292827, 0.90450293, 0.39530043, 0.10822607]])

In [15]:
#element-wise addition, subtraction, multiplication and division

print(rand_arr + 10)
print(rand_arr - 10)
print(rand_arr * 10)
print(rand_arr / 10)

[[10.04836202 10.47515613 10.68620383 10.0693193  10.47258702]
 [10.93633212 10.52978533 10.51094005 10.14810508 10.19461213]
 [10.94121222 10.91929442 10.85673321 10.49717124 10.50485445]
 [10.20713655 10.83340237 10.80126429 10.75208897 10.13026511]
 [10.35325222 10.79292827 10.90450293 10.39530043 10.10822607]]
[[-9.95163798 -9.52484387 -9.31379617 -9.9306807  -9.52741298]
 [-9.06366788 -9.47021467 -9.48905995 -9.85189492 -9.80538787]
 [-9.05878778 -9.08070558 -9.14326679 -9.50282876 -9.49514555]
 [-9.79286345 -9.16659763 -9.19873571 -9.24791103 -9.86973489]
 [-9.64674778 -9.20707173 -9.09549707 -9.60469957 -9.89177393]]
[[0.48362024 4.75156125 6.86203833 0.693193   4.72587024]
 [9.36332123 5.2978533  5.10940054 1.48105085 1.94612126]
 [9.41212221 9.19294424 8.56733211 4.97171244 5.04854446]
 [2.07136547 8.33402368 8.01264291 7.52088968 1.30265105]
 [3.53252219 7.92928272 9.0450293  3.95300432 1.08226073]]
[[0.0048362  0.04751561 0.06862038 0.00693193 0.0472587 ]
 [0.09363321 0.0529

In [16]:
# We can use built in methods also for the above operations 

arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

[ 9 11 13]


In [17]:
np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

[1 2 3]


In [18]:
np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[1 4 9]


In [20]:
# element-wise exponentiation
print(np.exp(arr1))

[2.71828183e+00 5.45981500e+01 8.10308393e+03]


In [22]:
# element-wise logorithm natural log
print(np.log(arr1)) 

[0.         1.38629436 2.19722458]


In [23]:
# base 2
print(np.log2(arr1))

[0.       2.       3.169925]


In [24]:
# square root 
print(np.sqrt(arr1))

[1. 2. 3.]


In [26]:
# Sine and cosine 

print(np.sin(arr1))
print(np.cos(arr1))

[ 0.84147098 -0.7568025   0.41211849]
[ 0.54030231 -0.65364362 -0.91113026]


### Assignment

1. How to get the max and min value in 1 and 2 dimensional array ?
2. How to get the max and min value along a speccified axis?
3. Compute the indices of the min and max along a specified axis?
4. Compute element-wise min and max of two arrays?
5. Compute the mean, median , percentile , sd and variance

## Sampling methods 

In [27]:
# generate a random scalar
print(np.random.rand()) 

0.17240324361139503


In [28]:
# generate a 1-D array
print(np.random.rand(3))

[0.40221127 0.58940701 0.28811124]


In [29]:
# generate a 2-D array
print(np.random.rand(3,3))

[[0.03740326 0.057525   0.13351603]
 [0.77023397 0.55190964 0.13804687]
 [0.97175347 0.01437481 0.84717654]]


In [30]:
#generate a sample from the standard normal distribution (mean = 0, var = 1)
print(np.random.randn(3,3))

[[ 1.73801299 -0.47327589 -0.94866161]
 [ 1.8833937  -1.09240633  0.95556488]
 [-1.46997798  0.66969971 -1.0733575 ]]


In [31]:
#generate an array of random integers in a given interval [low, high)
print(np.random.randint(1, 10, 3, 'i8'))

[2 1 1]


In [32]:
#generate an array of random floating-point numbers in the interval [0.0, 1.0)
# the following methods are the same as np.random.rand()

print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.9866385  0.25305033 0.18003328 0.52113263 0.26529041 0.29664479
 0.68543184 0.01191174 0.05493627 0.38282074]
[0.93709732 0.85738815 0.2213733  0.56279064 0.17848989 0.20414244
 0.00247079 0.02367218 0.34988518 0.83676174]
[0.76338408 0.05705871 0.96510763 0.80831144 0.4801008  0.24594675
 0.64096925 0.28111352 0.17258816 0.83457041]
[7.28173041e-01 6.04285518e-01 4.05570618e-05 4.33641846e-01
 8.42262090e-01 8.81455399e-01 7.62237557e-01 5.05493185e-01
 6.49289641e-02 9.12102478e-02]


### Assignment

1. How to generate a random sample from a given 1-d array 
2. How to shuffle the values of the array?
3. How to calculate the permutation using the array ?

## Linear Algebra 

In [33]:
# # we can do matrix multiplication
print(mat)
print(vec)
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]
[1 2 3]
[ 8 41 44]


In [34]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [35]:
## QR factorization
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-0.56368115  0.07681183 -0.43946335  0.41760492 -0.55573518]
 [-0.6151383  -0.19327069  0.30232027  0.34043371  0.61396959]
 [-0.08122864 -0.93490455  0.00124593 -0.2515301  -0.2368258 ]
 [-0.26570276  0.19994882  0.78709052 -0.20334718 -0.47808048]
 [-0.47610124  0.206689   -0.30977634 -0.7778776   0.17190793]]
[[-1.49903101e+00 -9.73580014e-01 -1.04461977e+00 -7.13501010e-01
  -1.26930088e+00]
 [ 0.00000000e+00 -8.17452778e-01 -4.10871255e-01 -4.90406692e-01
  -7.48725377e-01]
 [ 0.00000000e+00  0.00000000e+00  8.58519664e-01  4.11496548e-01
   5.53562298e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.74753619e-01
   2.72688234e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -8.47085885e-03]]


In [36]:
#singular value decomposition (SVD)
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.49888665  0.5652113   0.39265795 -0.33717711 -0.40469695]
 [-0.42398322 -0.55092405 -0.47209966 -0.32768389 -0.43181721]
 [-0.28001797 -0.24225954  0.30847637  0.79902924 -0.35957593]
 [-0.60676168  0.3074573  -0.46181485  0.28151901  0.49475688]
 [-0.35324289 -0.4730742   0.56081282 -0.24745539  0.52504768]]
[2.73666541 0.93905728 0.78989529 0.3286174  0.01492684]
[[-0.42181986 -0.38732989 -0.56704367 -0.36419731 -0.46676049]
 [ 0.35155228 -0.38899902 -0.09433906 -0.60499014  0.59175825]
 [-0.19051555 -0.78812164  0.50219034  0.30007855 -0.01805068]
 [ 0.66523986 -0.27788867 -0.47464011  0.47684519 -0.1660399 ]
 [-0.46865632 -0.0172477  -0.43827302  0.42885752  0.63565852]]


In [37]:
#compute eigen values
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.41910042+0.j         -0.04392984+0.44857592j -0.04392984-0.44857592j
  0.04370221+0.j          0.6467223 +0.j        ]


In [38]:
# eigen values decomposition 

arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.65019557+0.j         -0.0373818 +0.50809476j -0.0373818 -0.50809476j
 -0.32279772+0.j          0.2299183 +0.j        ]
[[ 0.4014511 +0.j          0.22165829+0.14194938j  0.22165829-0.14194938j
  -0.34833052+0.j          0.34187497+0.j        ]
 [ 0.46731377+0.j         -0.354034  -0.32970163j -0.354034  +0.32970163j
   0.06551159+0.j         -0.08664256+0.j        ]
 [ 0.27339615+0.j         -0.06839154+0.39553572j -0.06839154-0.39553572j
   0.18513533+0.j         -0.68570574+0.j        ]
 [ 0.39659301+0.j          0.59128845+0.j          0.59128845-0.j
  -0.59291718+0.j         -0.2877135 +0.j        ]
 [ 0.62323621+0.j         -0.33704884-0.26893284j -0.33704884+0.26893284j
   0.69896223+0.j          0.56801685+0.j        ]]


In [39]:
# compute trace and determinant 

# notice this is not a function in linalg!!!
print(np.trace(arr))  

2.482552546975861


In [40]:
print(np.linalg.det(arr))

-0.051052359238810616
